fix: build failure due to missing include on QDBusMetaType
Fixes the following build failure:

```
/build/deepin-control-center/src/dde-control-center-5.4.47/src/frame/window/modules/network/connectioneditpage.cpp: In member function ‘void dccV20::network::ConnectionEditPage::prepareConnection()’:
/build/deepin-control-center/src/dde-control-center-5.4.47/src/frame/window/modules/network/connectioneditpage.cpp:354:9: error: ‘qDBusRegisterMetaType’ was not declared in this scope; did you mean ‘qRegisterMetaType’?
  354 |         qDBusRegisterMetaType<QByteArrayList>();
      |         ^~~~~~~~~~~~~~~~~~~~~
      |         qRegisterMetaType
/build/deepin-control-center/src/dde-control-center-5.4.47/src/frame/window/modules/network/connectioneditpage.cpp:354:45: error: expected primary-expression before ‘>’ token
  354 |         qDBusRegisterMetaType<QByteArrayList>();
      |                                             ^
/build/deepin-control-center/src/dde-control-center-5.4.47/src/frame/window/modules/network/connectioneditpage.cpp:354:47: error: expected primary-expression before ‘)’ token
  354 |         qDBusRegisterMetaType<QByteArrayList>();
      |                                               ^
```

Log: